import { useEffect } from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

import SelectedAds from "../components/SelectedAds";
import HeroSection from "../pages/home/sections/HeroSection";
import OurDealSection from "./home/sections/OurDealSection";
import { getNewArrivals, getOnSaleProducts } from "../store/actions/product";

export default function Home() {
  const dispatch = useDispatch();

  const { newArrivals } = useSelector((state) => state.products);
  const { onSaleProducts } = useSelector((state) => state.products);

  useEffect(() => {
    dispatch(getNewArrivals({ CategoryId: 40 }));
    dispatch(getOnSaleProducts({ CategoryId: 40 }));
  }, []);

  return (
    <>
      <Head>
        <title>Ali's Boutique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-100">
        <HeroSection />
        <OurDealSection />

        {newArrivals?.length > 0 && (
          <SelectedAds title="new arrivals" list={newArrivals} />
        )}

        {onSaleProducts?.length > 0 && (
          <SelectedAds title="sale" list={onSaleProducts} />
        )}
      </main>
    </>
  );
}
