import { useEffect } from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

import SelectedAds from "../components/SelectedAds";
import HeroSection from "../pages/home/sections/HeroSection";
import OurDealSection from "./home/sections/OurDealSection";
import ProductsTodaySection from "./home/sections/ProductsTodaySection";
import { getNewArrivals } from "../store/actions/product";

export default function Home() {
  const dispatch = useDispatch();
  const { newArrivals } = useSelector((state) => state.products);

  useEffect(() => {
    dispatch(getNewArrivals({ category: "shirts", CategoryId: 40 }));
  }, []);

  return (
    <>
      <Head>
        <title>Ali's Boutique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-100">
        <HeroSection />
        <OurDealSection />

        {newArrivals.length > 0 && <SelectedAds list={newArrivals} />}

        <ProductsTodaySection />
      </main>
    </>
  );
}
